openapi: 3.0.1
info:
  version: 0.1.0
  title: Selma-EN (enskild näringsidkare)
  description:
    Detta API definierar den informationsmängd som flyter mellan GUI och LP-REST API för
  termsOfService: terms
  contact:
    name: Kjell Almgren
    email: kjell.almgren@landshypotek.se
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
tags:
  - name: Selma digitalt inträde för enskild näringsidkare
    description: Selma SME-Light
paths:
  /v1/common/listobjectwithloan:
    get:
      tags:
        - listobjectwithloan
      summary: get a list of objects for loan (ändamål)
      description: Returnerar en förekomst, ändamål och syfte för lånet
      operationId: GetObjectWithLoan
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListObjectWithLoan'
        '403':
          description: Forbidden
        '404':
          description: Invalid page
  /v1/common/listpurposewithloan:
    get:
      tags:
        - listobjectforloan
      summary: get a list of purposes with the loan
      description: Returnerar en lista på syfte för lånet
      operationId: ListPurposeWithLoan
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListPurposeWithLoan'
        '403':
          description: Forbidden
        '404':
          description: Invalid page
servers:
  - url: 'http://localhost:8000/'
  - url: 'https://localhost:8000/'
components:
  schemas:
    ListObjectsWithLoan:
      type: array
      items:
        type: object
      required:
        - id
      properties:
        id:
          type: string
          format: string
    ListPurposesWithLoan:
      type: array
      items:
        type: object
      properties:
        id:
          type: string
          format: string
        name:
          type: string
          format: string

