openapi: 3.0.1
info:
  version: 0.2.2
  title: Selma SME Light
  description: >-
    This model is the API between customer SME-Gui and the persistence framework base on Activiti
  termsOfService: terms
  contact:
    name: Kjell Almgren
    email: kjell.almgren@landshypotek.se
  license:
    name: MIT
    url: 'http://opensource.org/licenses/MIT'
tags:
  - name: Selma SME(EN) API Definitions
    description: Access layer of the process engine
paths:
  #
  # get a specific customer
  /v1/Customer/{processId}/{customerId}:
    get:
      tags:
        - getCustomer
      summary: Get a specific customer by ProcessId, customerId
      description: Get a specific customer from the process layer
      operationId: getCustomer
      parameters:
        # parameters required for getCustomer request
        - $ref: '#/components/parameters/processId'
        - $ref: '#/components/parameters/customerId'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '403':
          description: Forbidden
        '404':
          description: Invalid page
  #
  # Get a list of available customer for a given processId in Activiti
  ##
  /v1/Customers/{processId}:
    get:
      tags:
        - getCustomers
      summary: get a list of available customers
      description: Get a list of available customers by ProcessId....
      operationId: getCustomers
      parameters:
        # parameters required for getCustomers request
        - $ref: '#/components/parameters/processId'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customers'
        '403':
          description: Forbidden
        '404':
          description: Invalid page
        '500':
          description: Page Not found
  #
  # Update of a specific customerId
  #
  /v1/{processId}/{customerId}:
    post:
      tags:
        - CustomerUpdate
      summary: update a specific customer in Activiti
      description: descripition
      operationId: updateCustomer
      parameters:
      # required parameters to update a customer in Activiti
        - $ref: '#/components/parameters/processId'
        - $ref: '#/components/parameters/customerId'
      requestBody:
        $ref: '#/components/requestBodies/customerUpdate'
      responses:
        '200':
          description: Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '403':
          description: Forbidden
        '404':
          description: Invalid page
        '500':
          description: Page Not found
#
# Defined servers for the API
#
servers:
  - url: 'http://localhost:8000/'
  - url: 'https://localhost:8000/'
  
components:
  schemas:
    processId:
      description: Activiti framework unique identification
      type: string
      example: 12
    customerId:
      description: >-
        customerId is swedish ssn or corporate organisation number
      type: string
      example: 197001010101
    customerName:
      description: Full name of the customer/applicant
      type: string
      example: Anna Andersson
    customerRole:
      description: Huvudlåntagare or Medlåntagare i SAP
      type: string
      example: Huvudlåntagare

    customerType:
      description: Type of customer
      type: object
      required:
        - processId
        - customerId
      properties:
        processId:
          $ref: '#/components/schemas/processId'    
        customerId:
          $ref: '#/components/schemas/customerId'
        customerName:
          $ref: '#/components/schemas/customerName'
        role:
          $ref: '#/components/schemas/customerRole'
    
    Customer:
      $ref: '#/components/schemas/customerType'
    
    Customers:
      description: List of customerType
      type: array
      items:
        $ref: '#/components/schemas/customerType'
  
  parameters:
  #
  #####################################################
  # Predefined Parameters
  #####################################################
  #
    processId:
      name: processId
      in: path
      description: >- 
        unique identity in Activiti framework
      required: true
      schema:
        $ref: '#/components/schemas/processId'
    customerId:
      name: customerId
      in: path
      description: >- 
        customerId is swedish ssn or corporate organisation number
      required: true
      schema:
        $ref: '#/components/schemas/customerId'
  #
  #####################################################
  # Reuseable request bodies
  #####################################################
  #
  requestBodies:
    customerUpdate:
      description: Update a specific customer in the Activiti framwork
      required: true
      content: 
        application/json:
          schema:
            oneOf: 
              - $ref: "#/components/schemas/customerType"
      
        